import store from "../store/index.js"
const path=[
	{
		path:'/pages/index/index',
		"aliasPath":"/",
		name:'index'
	},
	{
		path:'/pages/index/Indent/Indent',
		name:'Indent'
	},
	{
		path:'/pages/send/send',
		name:'send'
	},
	{
		path:'/pages/inquire/inquire',
		name:'inquire'
	},
	{
		path:'/pages/my/my',
		name:'my'
	},
	{
		path:'/pages/index/DataItem/DataItem',
		name:'DataItem'
	},
	{
		path:'/pages/my/login/login',
		name:'mylogin',
		beforeEnter:((to, from, next)=>{
			if(store.state.address.usename){
				next()
			}else{
				next({name:'login'})
			}
		})
	},
	{
		path:'/pages/my/login/login_model/login_model',
		name:'login_model'
	},
	{
		path:'/pages/my/my-phone/my-phone',
		name:'my-phone'
	},
	{
		path:'/pages/my/my-autonym/my-autonym',
		name:'my-autonym'
	},
	{
		path:'/pages/my/my-reel/my-reel',
		name:'my-reel'
	},
	{
		path:'/pages/my/my-address/my-address',
		name:'my-address'
	},
	{
		path:'/pages/my/my-message/my-message',
		name:'my-message'
	},
	{
		path:'/pages/my/my-service/my-service',
		name:'my-service'
	},
	{
		path:'/pages/inquire/login/login',
		name:'login'
	},
]

export default path